//baneados By SrNadien
ServerEvents.recipes(nadien => {
    nadien.remove({output: [
        'industrialforegoing:hydroponic_bed',
        'reliquary:holy_hand_grenade',
        'reliquary:magicbane',
        'ae2wtlib:magnet_card',
        'industrialforegoing:mycelial_disenchantment',
        'industrialforegoing:enchantment_sorter',
        'industrialforegoing:enchantment_extractor',
        'industrialforegoing:enchantment_factory',
        'ae2:tiny_tnt',
        'minecraft:tnt',
        'gag:fishing_dynamite',
        'gag:mining_dynamite',
        'forbidden_arcanus:quantum_catcher',
        'artifacts:universal_attractor',
       'mekanismgenerators:electromagnetic_coil',
       'mekanismgenerators:turbine_casing',
       'mekanismgenerators:turbine_casing',
       'mekanismgenerators:turbine_valve',
       'mekanismgenerators:turbine_blade',
       'mekanismgenerators:turbine_rotor',
       'mekanismgenerators:saturating_condenser',
       'mekanismgenerators:rotational_complex',
       'mekanismgenerators:advanced_solar_generator',
       'mekanismgenerators:wind_generator',
    'minecraft:bundle',
    'gag:mining_dynamite',
    'gag:fishing_dynamite',
    'ars_nouveau:glyph_lightning',
    'ars_nouveau:glyph_explosion',
    'ars_nouveau:glyph_launch',
    'ars_nouveau:glyph_break',
    'ae2wtlib:magnet_card',
    'mekanism:module_magnetic_attraction_unit',
    'enderio:electromagnet',
    'artifacts:universal_attractor',
    'immersiveengineering:toolbox',
    'reliquary:alkahestry_tome',
    'industrialforegoing:infinity_nuke',
    'enchanted:enchanted_broomstick',
    'enchanted:broom',
    'industrialforegoing:enchantment_extractor',
    'mekmm:scrap_box',
    'rftoolsutility:spawner',
    'justdynathings:ticker',
    'immersiveengineering:toolbox', 
    'ae2:tiny_tnt', 
    'industrialforegoing:enchantment_extractor', 
    'sophisticatedbackpacks:advanced_magnet_upgrade', 
    'advanced_ae:pick_craft_card', 
    'apothic_enchanting:ender_lead', 
    'justdynathings:advanced_time_wand', 
    'justdirethings:time_wand',
    'minecraft:tnt',
    'ars_nouveau:storage_lectern', 
    'customnpcs:npcmounter', 
    'advanced_ae:auto_stock_card', 
    'apothic_enchanting:occult_ender_lead', 
    'customnpcs:npcsoulstoneempty', 
    'industrialforegoing:mechanical_dirt', 
    'advanced_ae:magnet_card', 
    'customnpcs:npcborder', 
    'enchanted:broom', 
    'curvy_pipes:huge_item_pipe', 
    'customnpcs:nbt_book', 
    'customnpcs:npcredstoneblock', 
    'advanced_ae:hp_buffer_card', 
    'advanced_ae:regeneration_card', 
    'irregular_implements:ender_letter', 
    'pickletweaks:magnet', 
    'sophisticatedstorage:magnet_upgrade', 
    'ae2:cell_workbench', 
    'industrialforegoing:infinity_nuke', 
    'advanced_ae:camo_card', 
    'advanced_ae:strength_card', 
    'advanced_ae:luck_card', 
    'mob_grinding_utils:xpsolidifier', 
    'apothic_enchanting:occult_ender_lead', 
    'customnpcs:npcteleporter', 
    'sophisticatedstorage:advanced_magnet_upgrade', 
    'customnpcs:npccopyblock', 
    'industrialforegoing:enchantment_factory', 
    'customnpcs:npcmailbox',
    ]
})


nadien.remove({id: 'utilitarian:utility/tnt_minecart'})



})